### ISSUE TITLE
default config is wrong if there's a virtual env in the project

### ISSUE THREAD

**Issue by apotterri** [getappmap/appmap-python#245]
When `appmap` creates a default config for a project directory that contains a virtual environment, it includes all the packages installed in the venv. This isn't desirable and causes various failures.

If possible, it should detect a directory that's a venv and ignore it.

**Comment by dustinbyrne** [comment]
What are the steps required to reproduce this? I've installed `appmap` in a new directory containing a venv with some packages, but the resulting appmap.yml only contains
```yml
appmap_dir: tmp/appmap
language: python
name: test
packages: []
```
